---
- name: Setup env
  hosts: all

  roles:
    - { role: update-packages, become: true }
    - { role: regolith, become: true }
    - { role: common, become: true }
    - { role: brave, become: true }
    - { role: chrome, become: true }
    - { role: vscode, become: true }
    - { role: 1password, become: true }
    - { role: config, become: true }
    - { role: zsh, become: true }
