---
- name: Setup env
  hosts: all

  roles:
    - { role: update-packages, become: true }
    - { role: regolith, become: true }
    - { role: common, become: true }
    - { role: vscode, become: true }
