---
- name: Download the Regolith public key
  ansible.builtin.get_url:
    url: https://regolith-desktop.org/regolith.key
    dest: /tmp/regolith.key
    mode: "0644"

- name: Register the Regolith public key
  ansible.builtin.command:
    cmd: gpg --dearmor -o /usr/share/keyrings/regolith-archive-keyring.gpg /tmp/regolith.key
    creates: /usr/share/keyrings/regolith-archive-keyring.gpg

- name: Add Regolith repository
  ansible.builtin.copy:
    content: |
      deb [arch=amd64 signed-by=/usr/share/keyrings/regolith-archive-keyring.gpg] https://regolith-desktop.org/release-3_2-ubuntu-noble-amd64 noble main
    dest: /etc/apt/sources.list.d/regolith.list
    mode: "0644"

- name: Update apt
  ansible.builtin.apt:
    update_cache: true

- name: Install Regolith desktop
  ansible.builtin.apt:
    name:
      - regolith-desktop
      - regolith-session-flashback
      - regolith-look-lascaille
      - i3xrocks-net-traffic
      - i3xrocks-cpu-usage
      - i3xrocks-time
      - i3xrocks-battery
      - i3xrocks-memory
      - i3xrocks-wifi
      - i3xrocks-temp
    state: present

- name: Remove config folder
  ansible.builtin.file:
    path: "/home/{{ user }}/.config/regolith3"
    state: absent

- name: Create a symlink to configuration folder
  ansible.builtin.file:
    src: "/home/{{ user }}/dotts/config/regolith"
    dest: "/home/{{ user }}/.config/regolith3"
    state: link
    owner: "{{ user }}"
    group: "{{ user }}"
