---
- name: Check if .zshrc exists
  ansible.builtin.stat:
    path: /home/{{ user }}/.zshrc
  register: file_zshrc

- name: Create a symlink for zshrc
  ansible.builtin.file:
    src: "/home/{{ user }}/dotts/config/zsh/.zshrc"
    dest: "/home/{{ user }}/.zshrc"
    state: link
    owner: "{{ user }}"
    group: "{{ user }}"
  when: not file_zshrc.stat.exists

- name: Check if .power10k exists
  ansible.builtin.stat:
    path: /home/{{ user }}/.p10k.zsh
  register: file_power10k

- name: Create a symlink for power10k
  ansible.builtin.file:
    src: "/home/{{ user }}/dotts/config/p10k/.p10k.zsh"
    dest: "/home/{{ user }}/.p10k.zsh"
    state: link
    owner: "{{ user }}"
    group: "{{ user }}"
  when: not file_power10k.stat.exists

- name: Install common lib with apt
  ansible.builtin.apt:
    name:
      - zsh
    state: present

- name: Change default shell to zsh
  ansible.builtin.user:
    name: "{{ user }}"
    shell: /usr/bin/zsh

- name: Check if Oh My Zsh is already installed
  ansible.builtin.stat:
    path: "/home/{{ user }}/.oh-my-zsh"
  register: ohmyzsh_check

- name: Download Oh My Zsh installation script
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
    dest: /tmp/install_ohmyzsh.sh
    mode: "0777"
    owner: "{{ user }}"
    group: "{{ user }}"

- name: Run Oh My Zsh installation script
  ansible.builtin.command: sh /tmp/install_ohmyzsh.sh --unattended
  become_user: "{{ user }}"
  register: ohmyzsh_result
  failed_when: "'FAILED' in ohmyzsh_result.stderr"
  changed_when: ohmyzsh_result.rc != 0

- name: Clone the Powerlevel10k repository # noqa: latest
  ansible.builtin.git:
    repo: https://github.com/romkatv/powerlevel10k.git
    dest: "/home/{{ user }}/.oh-my-zsh/custom/themes/powerlevel10k"
    depth: 1
  become_user: "{{ user }}"
  register: power10k_result
  changed_when: power10k_result.after != power10k_result.before
