---
- name: Add Brave GPG key
  ansible.builtin.apt_key:
    url: https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg
    keyring: /usr/share/keyrings/brave-browser-archive-keyring.gpg
    state: present

- name: Add the Brave APT repository
  ansible.builtin.lineinfile:
    path: /etc/apt/sources.list.d/brave-browser-release.list
    line: "deb [signed-by=/usr/share/keyrings/brave-browser-archive-keyring.gpg] https://brave-browser-apt-release.s3.brave.com/ stable main"
    create: true
    mode: "0600"

- name: Update apt cache and install 1Password
  ansible.builtin.apt:
    update_cache: true
    name: brave-browser
    state: present
