---
- name: Add Google Chrome GPG key
  ansible.builtin.apt_key:
    url: https://dl-ssl.google.com/linux/linux_signing_key.pub
    keyring: /usr/share/keyrings/google-chrome-archive-keyring.gpg
    state: present

- name: Add the Google Chrome APT repository
  ansible.builtin.lineinfile:
    path: /etc/apt/sources.list.d/google-chrome.list
    line: "deb [signed-by=/usr/share/keyrings/google-chrome-archive-keyring.gpg] https://dl.google.com/linux/chrome/deb/ stable main"
    create: true
    mode: "0644"

- name: Update apt cache and install Google Chrome
  ansible.builtin.apt:
    update_cache: true
    name: google-chrome-stable
    state: present
