---
- name: Install common lib
  ansible.builtin.apt:
    name:
      - wget
      - curl
      - gpg
      - python3
      - python-is-python3
      - i3xrocks-battery
      - i3xrocks-memory
      - i3xrocks-wifi
      - i3xrocks-temp
      - htop
      - vim
      - zsh
      - xcwd
      - ansible-lint
    state: present
