---
- name: Install common lib with apt
  ansible.builtin.apt:
    name:
      - wget
      - curl
      - gpg
      - python3
      - python-is-python3
      - i3xrocks-battery
      - i3xrocks-memory
      - i3xrocks-wifi
      - i3xrocks-temp
      - htop
      - vim
      - xcwd
      - ansible-lint
      - python3-pip
      - gpaste-2
      - fzf
      - flameshot
      - mysql-client
      - postgresql-client
      - alacritty
    state: present

- name: Install common lib with snap
  community.general.snap:
    name:
      - slack
      - vlc
      - dbeaver-ce
