---
- name: Download and add the 1Password GPG key
  ansible.builtin.get_url:
    url: https://downloads.1password.com/linux/keys/1password.asc
    dest: /tmp/1password.asc
    mode: '0644'

- name: Add 1Password GPG key
  ansible.builtin.apt_key:
    url: https://downloads.1password.com/linux/keys/1password.asc
    keyring: /usr/share/keyrings/1password-archive-keyring.gpg
    state: present

- name: Add the 1Password APT repository
  ansible.builtin.lineinfile:
    path: /etc/apt/sources.list.d/1password.list
    line: 'deb [arch=amd64 signed-by=/usr/share/keyrings/1password-archive-keyring.gpg] https://downloads.1password.com/linux/debian/amd64 stable main'
    create: true
    mode: "0600"

- name: Create the necessary directory for debsig policy
  ansible.builtin.file:
    path: /etc/debsig/policies/AC2D62742012EA22/
    state: directory
    mode: '0755'

- name: Download the 1Password debsig policy file
  ansible.builtin.get_url:
    url: https://downloads.1password.com/linux/debian/debsig/1password.pol
    dest: /etc/debsig/policies/AC2D62742012EA22/1password.pol
    mode: '0644'

- name: Create the necessary directory for debsig keyring
  ansible.builtin.file:
    path: /usr/share/debsig/keyrings/AC2D62742012EA22/
    state: directory
    mode: '0755'

- name: Add the debsig GPG key to the keyring
  ansible.builtin.apt_key:
    url: https://downloads.1password.com/linux/keys/1password.asc
    keyring: /usr/share/debsig/keyrings/AC2D62742012EA22/debsig.gpg
    state: present

- name: Update apt cache and install 1Password
  ansible.builtin.apt:
    update_cache: true
    name: 1password
    state: present
